CREATE  TABLE if not EXISTS USERS (
  ID INT IDENTITY PRIMARY KEY,
  USER_ID VARCHAR UNIQUE,
  USER_PW VARCHAR,
  USER_NAME VARCHAR UNIQUE,
  LEVEL INT DEFAULT 1,
  JOB_ID INT,
  MAP_ID INT DEFAULT 1,
  X INT DEFAULT 100,
  Y INT DEFAULT 100,
  LAST_LOGIN DATETIME
);