CREATE  TABLE if not EXISTS USERS (
  ID INT IDENTITY PRIMARY KEY ,
  USER_ID VARCHAR UNIQUE ,
  USER_PW VARCHAR ,
  USER_NAME VARCHAR UNIQUE ,
  LEVEL INT,
  JOB_ID INT,
  MAP_ID INT,
  X INT,
  Y INT,
  LAST_LOGIN DATETIME
);